[2025-04-18T17:12:32.340+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T17:12:32.349+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_yf_scraper.store_into_summary_table manual__2025-04-18T09:08:53.126903+00:00 [queued]>
[2025-04-18T17:12:32.358+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_yf_scraper.store_into_summary_table manual__2025-04-18T09:08:53.126903+00:00 [queued]>
[2025-04-18T17:12:32.358+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-18T17:12:32.369+0800] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): store_into_summary_table> on 2025-04-18 09:08:53.126903+00:00
[2025-04-18T17:12:32.373+0800] {standard_task_runner.py:72} INFO - Started process 31784 to run task
[2025-04-18T17:12:32.377+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_yf_scraper', 'store_into_summary_table', 'manual__2025-04-18T09:08:53.126903+00:00', '--job-id', '468', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/xg/h9xj0trn3dxds251bj2q6hf80000gn/T/tmpqjvs5wun']
[2025-04-18T17:12:32.378+0800] {standard_task_runner.py:105} INFO - Job 468: Subtask store_into_summary_table
[2025-04-18T17:12:32.411+0800] {task_command.py:467} INFO - Running <TaskInstance: reddit_yf_scraper.store_into_summary_table manual__2025-04-18T09:08:53.126903+00:00 [running]> on host ervins-macbook-air-2.local
[2025-04-18T17:12:32.605+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_yf_scraper' AIRFLOW_CTX_TASK_ID='store_into_summary_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T09:08:53.126903+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T09:08:53.126903+00:00'
[2025-04-18T17:12:32.605+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-18T17:12:32.605+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-18T17:12:32.606+0800] {logging_mixin.py:190} INFO - Current task name:store_into_summary_table state:running start_date:2025-04-18 09:12:32.349535+00:00
[2025-04-18T17:12:32.606+0800] {logging_mixin.py:190} INFO - Dag name:reddit_yf_scraper and current dag run status:running
[2025-04-18T17:12:32.606+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T17:12:36.720+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 508, in store_into_summary_table
    load_job.result()
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 969, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 1; errors: 6; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 1; errors: 6; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: Missing close quote character (").; line_number: 3 byte_offset_to_start_of_line: 2426 column_index: 7 column_name: "Summary" column_type: STRING value: "Investor note: AA..."; reason: invalid, message: Error while reading data, error message: Missing close quote character (").; line_number: 6 byte_offset_to_start_of_line: 5382 column_index: 7 column_name: "Summary" column_type: STRING value: "The sentiment aro..."; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 1 columns.; line_number: 4 byte_offset_to_start_of_line: 5020 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 1 columns.; line_number: 7 byte_offset_to_start_of_line: 7808 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 3 columns.; line_number: 5 byte_offset_to_start_of_line: 5021 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 2 columns.; line_number: 8 byte_offset_to_start_of_line: 7809 column_index: 7 column_name: "Summary" column_type: STRING
[2025-04-18T17:12:36.735+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-18T17:12:36.735+0800] {logging_mixin.py:190} INFO - Task start:2025-04-18 09:12:32.349535+00:00 end:2025-04-18 09:12:36.734642+00:00 duration:4.385107
[2025-04-18T17:12:36.736+0800] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): store_into_summary_table> dag:<DAG: reddit_yf_scraper> dagrun:<DagRun reddit_yf_scraper @ 2025-04-18 09:08:53.126903+00:00: manual__2025-04-18T09:08:53.126903+00:00, state:running, queued_at: 2025-04-18 09:08:53.161335+00:00. externally triggered: True>
[2025-04-18T17:12:36.736+0800] {logging_mixin.py:190} INFO - Failure caused by 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 1; errors: 6; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 1; errors: 6; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: Missing close quote character (").; line_number: 3 byte_offset_to_start_of_line: 2426 column_index: 7 column_name: "Summary" column_type: STRING value: "Investor note: AA..."; reason: invalid, message: Error while reading data, error message: Missing close quote character (").; line_number: 6 byte_offset_to_start_of_line: 5382 column_index: 7 column_name: "Summary" column_type: STRING value: "The sentiment aro..."; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 1 columns.; line_number: 4 byte_offset_to_start_of_line: 5020 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 1 columns.; line_number: 7 byte_offset_to_start_of_line: 7808 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 3 columns.; line_number: 5 byte_offset_to_start_of_line: 5021 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 2 columns.; line_number: 8 byte_offset_to_start_of_line: 7809 column_index: 7 column_name: "Summary" column_type: STRING
[2025-04-18T17:12:36.737+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=reddit_yf_scraper, task_id=store_into_summary_table, run_id=manual__2025-04-18T09:08:53.126903+00:00, execution_date=20250418T090853, start_date=20250418T091232, end_date=20250418T091236
[2025-04-18T17:12:36.751+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T17:12:36.751+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 468 for task store_into_summary_table (400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 1; errors: 6; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 1; errors: 6; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: Missing close quote character (").; line_number: 3 byte_offset_to_start_of_line: 2426 column_index: 7 column_name: "Summary" column_type: STRING value: "Investor note: AA..."; reason: invalid, message: Error while reading data, error message: Missing close quote character (").; line_number: 6 byte_offset_to_start_of_line: 5382 column_index: 7 column_name: "Summary" column_type: STRING value: "The sentiment aro..."; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 1 columns.; line_number: 4 byte_offset_to_start_of_line: 5020 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 1 columns.; line_number: 7 byte_offset_to_start_of_line: 7808 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 3 columns.; line_number: 5 byte_offset_to_start_of_line: 5021 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 2 columns.; line_number: 8 byte_offset_to_start_of_line: 7809 column_index: 7 column_name: "Summary" column_type: STRING; 31784)
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 508, in store_into_summary_table
    load_job.result()
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/google/cloud/bigquery/job/base.py", line 969, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 1; errors: 6; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 1; errors: 6; max bad: 0; error percent: 0; reason: invalid, message: Error while reading data, error message: Missing close quote character (").; line_number: 3 byte_offset_to_start_of_line: 2426 column_index: 7 column_name: "Summary" column_type: STRING value: "Investor note: AA..."; reason: invalid, message: Error while reading data, error message: Missing close quote character (").; line_number: 6 byte_offset_to_start_of_line: 5382 column_index: 7 column_name: "Summary" column_type: STRING value: "The sentiment aro..."; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 1 columns.; line_number: 4 byte_offset_to_start_of_line: 5020 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 1 columns.; line_number: 7 byte_offset_to_start_of_line: 7808 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 3 columns.; line_number: 5 byte_offset_to_start_of_line: 5021 column_index: 7 column_name: "Summary" column_type: STRING; reason: invalid, message: Error while reading data, error message: CSV table references column position 7, but line contains only 2 columns.; line_number: 8 byte_offset_to_start_of_line: 7809 column_index: 7 column_name: "Summary" column_type: STRING
[2025-04-18T17:12:36.783+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-18T17:12:36.799+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T17:12:36.800+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
