[2025-04-18T22:11:39.634+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T22:11:39.642+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_yf_scraper.upload_yf_to_gcs manual__2025-04-18T14:05:53.430405+00:00 [queued]>
[2025-04-18T22:11:39.646+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_yf_scraper.upload_yf_to_gcs manual__2025-04-18T14:05:53.430405+00:00 [queued]>
[2025-04-18T22:11:39.646+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-18T22:11:39.651+0800] {taskinstance.py:2890} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_yf_to_gcs> on 2025-04-18 14:05:53.430405+00:00
[2025-04-18T22:11:39.656+0800] {standard_task_runner.py:72} INFO - Started process 96951 to run task
[2025-04-18T22:11:39.660+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_yf_scraper', 'upload_yf_to_gcs', 'manual__2025-04-18T14:05:53.430405+00:00', '--job-id', '526', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/2f/rw5w89ss6nl38qvq2cxrh29w0000gn/T/tmp5_vkrpl5']
[2025-04-18T22:11:39.661+0800] {standard_task_runner.py:105} INFO - Job 526: Subtask upload_yf_to_gcs
[2025-04-18T22:11:39.681+0800] {task_command.py:467} INFO - Running <TaskInstance: reddit_yf_scraper.upload_yf_to_gcs manual__2025-04-18T14:05:53.430405+00:00 [running]> on host yueyaos-macbook-pro.local
[2025-04-18T22:11:39.708+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_yf_scraper' AIRFLOW_CTX_TASK_ID='upload_yf_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T14:05:53.430405+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T14:05:53.430405+00:00'
[2025-04-18T22:11:39.709+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-18T22:11:39.709+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-18T22:11:39.709+0800] {logging_mixin.py:190} INFO - Current task name:upload_yf_to_gcs state:running start_date:2025-04-18 14:11:39.642850+00:00
[2025-04-18T22:11:39.709+0800] {logging_mixin.py:190} INFO - Dag name:reddit_yf_scraper and current dag run status:running
[2025-04-18T22:11:39.709+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T22:11:39.712+0800] {connection.py:277} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-04-18T22:11:39.714+0800] {base.py:84} INFO - Retrieving connection 'google_cloud_default'
[2025-04-18T22:11:39.715+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 115, in execute
    hook.upload(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 544, in upload
    client = self.get_conn()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 160, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 357, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 330, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 418, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 264, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 322, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/google/oauth2/service_account.py", line 260, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/test-62769-e009f254cc4b.json'
[2025-04-18T22:11:39.721+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-18T22:11:39.721+0800] {logging_mixin.py:190} INFO - Task start:2025-04-18 14:11:39.642850+00:00 end:2025-04-18 14:11:39.720901+00:00 duration:0.078051
[2025-04-18T22:11:39.721+0800] {logging_mixin.py:190} INFO - Task:<Task(LocalFilesystemToGCSOperator): upload_yf_to_gcs> dag:<DAG: reddit_yf_scraper> dagrun:<DagRun reddit_yf_scraper @ 2025-04-18 14:05:53.430405+00:00: manual__2025-04-18T14:05:53.430405+00:00, state:running, queued_at: 2025-04-18 14:05:53.438216+00:00. externally triggered: True>
[2025-04-18T22:11:39.721+0800] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/test-62769-e009f254cc4b.json'
[2025-04-18T22:11:39.722+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=reddit_yf_scraper, task_id=upload_yf_to_gcs, run_id=manual__2025-04-18T14:05:53.430405+00:00, execution_date=20250418T140553, start_date=20250418T141139, end_date=20250418T141139
[2025-04-18T22:11:39.734+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T22:11:39.735+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 526 for task upload_yf_to_gcs ([Errno 2] No such file or directory: '/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/test-62769-e009f254cc4b.json'; 96951)
Traceback (most recent call last):
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 115, in execute
    hook.upload(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 544, in upload
    client = self.get_conn()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 160, in get_conn
    credentials=self.get_credentials(), client_info=CLIENT_INFO, project=self.project_id
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 357, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/common/hooks/base_google.py", line 330, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 418, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 264, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 322, in _get_credentials_using_key_path
    credentials = google.oauth2.service_account.Credentials.from_service_account_file(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/google/oauth2/service_account.py", line 260, in from_service_account_file
    info, signer = _service_account_info.from_filename(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/google/auth/_service_account_info.py", line 78, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/test-62769-e009f254cc4b.json'
[2025-04-18T22:11:39.763+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-18T22:11:39.774+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T22:11:39.776+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
